birthday/urls.py
from django.urls import path
from . import views

app_name="birthday"

urlpatterns = [
    path("", views.index, name="index")
]

hello/urls.py
from django.urls import path
from . import views

app_name = "hello"
urlpatterns = [
    path("", views.index, name="index"),
    path("brian", views.brian, name="brian"),
    path("<str:name>", views.greet, name="greet")
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index")
]

lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('birthday/', include("birthday.urls")),
    path('tasks/', include("tasks.urls"))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

birthday/models.py
from django.db import models

# Create your models here.

hello/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

birthday/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    if (now.day == 1 and now.month == 10):
        birth = True
    else:
        birth = False
    return render(request, "birthday/index.html", {
        "birth": birth
    })

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian.")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "home/index.html")

tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
    "form": NewTaskForm()
    })

birthday/templates/birthday/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'birthday/style.css' %}">
    <title>Is it my Birthday ?</title>
</head>
<body>
    {% if birth %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greet</title>
</head>
<body>
    <h1>Hello, {{ name }} !</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, world !</h1>
</body>
</html>

home/templates/home/index.html
{% extends 'home/layout.html' %}

{% block title %}
ArsApp - Home
{% endblock %}

{% block body %}
    <h1>List of apps :</h1>
    <ul>
    <li><a href="{% url 'hello:index' %}">Hello</a></li>
    <li><a href="{% url 'birthday:index' %}">Is it my birthday ?</a></li>
    <li><a href="{% url 'tasks:index' %}">Tasks list</a></li>
    </ul>
{% endblock %}

home/templates/home/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block title %}
Add task
{% endblock %}

{% block body %}
    <h1>Add a new task :</h1>
    <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="/tasks">Return to tasks list</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block title %}
Tasks list
{% endblock %}

{% block body %}
    <h1>List of tasks :</h1>
    {% if tasks %}
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% endfor %}    
        </ul>
    {% else %}
        <p>No tasks yet !</p>
    {% endif %}
    <a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>